### ISSUE TITLE
Netherite smelting recipe needs to be removed

### ISSUE THREAD

**Issue by Polarite** [Polarite/NostalgiaBlast#41]
![image](https://user-images.githubusercontent.com/34978332/224088437-64a97598-5e59-4303-afd9-6953022c0546.png)

**Comment by Polarite** [comment]
![image](https://user-images.githubusercontent.com/34978332/224088603-6b210892-0df5-4f5e-a1e0-41573a1cff4b.png)

**Comment by ThatoneSkeleton1** [comment]
https://github.com/Polarite/NostalgiaBlast/commit/860a95955c47c70524b44713a5c06a9f29b6acc6
